// -------- 漫才データ（台本） --------
const manzaiData = {

    // -------- 北海道 -----------------------------------------------------------------------------------------------------
    'hokkaido': {
    scenario: [
            { type: 'dialogue', speaker: '北海道', text: 'はいどうも〜！<br>北海道と〜' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '北海道', text: '北海道といえば<br>やっぱデカい！' },
            { type: 'dialogue', speaker: '北海道', text: '土地も、イベントも<br>スケール感が売り！' },
            { type: 'dialogue', speaker: '北海道', text: 'さっぽろ雪まつりとかさ' },
            { type: 'dialogue', speaker: '山形', text: '“でっかいどう”ってやつだね' },
            { type: 'dialogue', speaker: '山形', text: '大規模イベントなら<br>山形にもあるよ' },
            { type: 'dialogue', speaker: '北海道', text: 'ほう<br>たとえば？' },
            { type: 'dialogue', speaker: '山形', text: 'たとえば、“人間将棋”' },
            { type: 'dialogue', speaker: '山形', text: '巨大な将棋盤の上を<br>人が駒となって動くんだ' },
            { type: 'dialogue', speaker: '北海道', text: '・・・ほう<br>他には？' },
            { type: 'dialogue', speaker: '山形', text: 'あと、日本一の<br>芋煮会フェスティバル' },
            {
             type: 'prompt', speaker: '山形',text: '直径6.5メートルの鍋と<br>バックホーを使って芋煮を作るんだ',
             promptText: '人が駒となって動く人間将棋と<br>巨大鍋とバックホーを使う芋煮会だよ',
                tsukkomi: [
                { text: "巨大化させた<br>だけかよ！", 
                    point: 3, type: ['t','p','v'],
                  reaction: '北海道「発想が小学生みたいだな！」' },
                { text: "重機使って<br>芋煮会！？", 
                    point: 1, type: ['v'],
                  reaction: '北海道「衛生面だけ気になるんだけど・・・」' },
                { text: "雪まつりと<br>戦えそう", 
                    point: 0, type: ['p','v'],
                  reaction: '北海道「盛り上がりそうだな！」' }
                ]
            },
            { type: 'dialogue', speaker: '北海道', text: '・・・まあ<br>スケールの話はさておき' },
            { type: 'dialogue', speaker: '北海道', text: '山形も一応、雪国だよな？' },
            { type: 'dialogue', speaker: '北海道', text: 'でも雪国って言ったら<br>やっぱ北海道っしょ' },
            { type: 'dialogue', speaker: '北海道', text: '夏でも涼しいし' },
            { type: 'dialogue', speaker: '北海道', text: '正直<br>暑さ対策で困ることは少ないな' },
            { type: 'dialogue', speaker: '山形', text: 'それは羨ましいなあ' },
            { type: 'dialogue', speaker: '山形', text: '山形の夏はすごく暑いから<br>暑さ対策は頑張ってるよ' },
            { type: 'dialogue', speaker: '山形', text: '「冷やし中華はじめました」<br>とか' },
            { type: 'dialogue', speaker: '北海道', text: 'おっ！やっぱ夏といえば<br>冷やし中華だよな〜' },
            { type: 'dialogue', speaker: '山形', text: '中華だけじゃなく・・・' },
            {
             type: 'prompt', speaker: '山形',text: '冷やしシャンプーとか<br>冷やしラーメンも始まるね',
                tsukkomi: [
                { text: "めっちゃ暑さに<br>弱いじゃん", 
                    point: 0, type: ['v'],
                  reaction: '北海道「もっと頑張れよ〜」' },
                { text: "冷やし中華と冷やしラーメン<br>何が違うの！？", 
                    point: 1, type: ['p','t'],
                  reaction: '山形「全然違うよ<br>食べてみる？」' },
                { text: "冷やせばいいと<br>思ってる！？", 
                    point: 3, type: ['t','p','v'],
                  reaction: '北海道「まあ<br>それが一番の近道か・・・」' }
                ]
            },
            { type: 'dialogue', speaker: '北海道', text: 'まあでもさ' },
            { type: 'dialogue', speaker: '北海道', text: '自然環境で言ったら<br>北海道は最強だよ' },
            { type: 'dialogue', speaker: '北海道', text: '世界遺産の知床もあるし<br>流氷も来るし、ヒグマも出るし' },
            { type: 'dialogue', speaker: '北海道', text: '山形も<br>そういう自然、ある？' },
            { type: 'dialogue', speaker: '山形', text: '山形は空気が綺麗なんだ<br>空気神社もあるし' },
            { type: 'dialogue', speaker: '北海道', text: 'ほう・・・' },
            { type: 'dialogue', speaker: '北海道', text: '・・・・・・<br>・・・・・・' },
            { type: 'dialogue', speaker: '北海道', text: '・・・え？空気神社？<br>なんの話？' },
            { type: 'dialogue', speaker: '山形', text: '空気があまりにも綺麗だから<br>感謝しようと思って' },
            {
                type: 'prompt',speaker: '山形',text: '空気を御神体とする神社が<br>できたんだよね',
                tsukkomi: [
                    { text: "北海道でも<br>やろうかな",
                        point: 0, type: ['v'],
                        reaction: '北海道「神社だらけになりそう」'},
                    { text: "感謝の仕方<br>独特すぎるだろ！",
                        point: 3, type: ['t','p','v'],
                        reaction: '北海道「スピってる！？大丈夫！？」'},
                    { text: "勝手に神様に<br>すんな！",
                        point: 1, type: ['t','p'],
                        reaction: '北海道「空気はみんなのものだろ！」'}
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '北海道', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '北海道', text: 'ツッコミどころが多いってことは<br>わかった' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '北海道', text: '・・・・・・' },
            { type: 'dialogue', speaker: '北海道', text: 'それでいいのかよ！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
    ]
    },

    // -------- 青森 --------------------------------------------------------------------------------------------------------
    'aomori': {
        scenario: [
            { type: 'dialogue', speaker: '青森', text: 'はいどうもー！<br>青森県だ！' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '青森', text: '青森どいえば<br>やっぱしリンゴだ！' },
            { type: 'dialogue', speaker: '青森', text: '生産量日本一！<br>一づのものを極めるのが青森の県民性よ' },
            { type: 'dialogue', speaker: '青森', text: '山形はさくらんぼの生産量が<br>日本一だよな？' },
            { type: 'dialogue', speaker: '山形', text: 'うん、あとラーメンの消費額も<br>日本一だよ' },
            { type: 'dialogue', speaker: '青森', text: 'ああ、山形は<br>ラーメン大好ぎだもんな' },
            { type: 'dialogue', speaker: '山形', text: '山形はラーメンと<br>そばが美味しいんだ' },
            { type: 'dialogue', speaker: '山形', text: 'それをアピールしようと思って<br>新しい名前がついたんだよね' },
            { type: 'dialogue', speaker: '青森', text: '新しい名前？<br>キャッチコピーみだいな？' },
            { type: 'dialogue', speaker: '山形', text: '山形県改め・・・' },
            {
                type: 'prompt', speaker: '山形', text: '「ラーメン県そば王国やまがた」だよ',
                tsukkomi: [
                    { text: "県の中さ王国<br>でぎでらんだげど！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '青森「行政区分どうなってんだ！<br>めちゃくちゃすぎる！」' },
                    { text: "名前<br>長すぎだべ！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '青森「住所書ぐどぎ大変すぎる！」' },
                    { text: "わがりやすくて<br>いいね", 
                        point: 0, type: ['v'], 
                        reaction: '青森「名物がひと目でわがる」' }
                ]
            },
            { type: 'dialogue', speaker: '青森', text: '手広ぐやりすぎだ・・・' },
            { type: 'dialogue', speaker: '青森', text: '青森は気候が厳しいからな<br>冬の寒さは半端でねじゃ' },
            { type: 'dialogue', speaker: '青森', text: 'だからこそ「<ruby>酸ヶ湯<rt>すかゆ</rt></ruby>温泉」みたいな<br>体の芯がらぬぐだまる温泉が最高なんだ' },
            { type: 'dialogue', speaker: '山形', text: 'あったかそうだねぇ' },
            { type: 'dialogue', speaker: '青森', text: 'けど、夏は他の地域さ比べて<br>涼しくて過ごしやすいんだ' },
            { type: 'dialogue', speaker: '山形', text: 'それは羨ましいなあ' },
            { type: 'dialogue', speaker: '山形', text: '山形の夏はすごく暑いから<br>暑さ対策は頑張ってるよ' },
            { type: 'dialogue', speaker: '山形', text: '「冷やし中華はじめました」<br>とか' },
            { type: 'dialogue', speaker: '青森', text: 'おっ！やっぱ夏どいえば<br>冷やし中華だよな〜' },
            { type: 'dialogue', speaker: '山形', text: '冷やし中華だけじゃなく・・・' },
            {
             type: 'prompt', speaker: '山形',text: '冷やしシャンプーとか<br>冷やしラーメンも始まるね',
             promptText: '冷やしシャンプーとか<br>冷やしラーメンも始まるね',
                tsukkomi: [
                { text: "シャンプーまで冷やさねんで<br>いいだろ！", 
                    point: 1, type: ['p','t'],
                  reaction: '青森「冷やさねんでも<br>ぬぐぐはねんだ！」' },
                { text: "なんでもかんでも冷やせば<br>いいど思ってるのがよ！", 
                    point: 3, type: ['t','p','v'],
                  reaction: '青森「そのうぢ<br>温泉まで冷やしそうだな！」' },
                { text: "クーラーの使用頻度<br>下がるな", 
                    point: 0, type: ['p'],
                  reaction: '青森「エコでいいな」' }
                ]
            },
            { type: 'dialogue', speaker: '青森', text: '涼み方のクセが強えな・・・' },
            { type: 'dialogue', speaker: '青森', text: 'でもな、冷やしてばかりじゃダメだ<br>青森の夏は短ぇんだぞ！' },
            { type: 'dialogue', speaker: '青森', text: 'その一瞬さ全での情熱賭げる！<br>それが「ねぶた祭」だ！' },
            { type: 'dialogue', speaker: '青森', text: '闇さ浮がぶ巨大な灯籠！<br>響ぎ渡るラッセラーの声！' },
            { type: 'dialogue', speaker: '青森', text: 'あの爆発的なエネルギーこそが<br>青森県民の魂なんだ！' },
            { type: 'dialogue', speaker: '山形', text: 'すごい迫力だよねぇ' },
            { type: 'dialogue', speaker: '山形', text: 'でも山形には<br>もっと静かなお祭りがあるよ' },
            { type: 'dialogue', speaker: '青森', text: 'すんずがな祭り？' },
            { type: 'dialogue', speaker: '青森', text: '花笠まづり・・・<br>は結構賑やがだし' },
            { type: 'dialogue', speaker: '山形', text: '「空気まつり」だよ' },
            { type: 'dialogue', speaker: '青森', text: '・・・空気まづり？' },
            { type: 'dialogue', speaker: '山形', text: '空気に感謝して建立された<br>「空気神社」のお祭りなんだけど' },
            { type: 'dialogue', speaker: '山形', text: '本殿がステンレスの鏡でできてて<br>空気が御神体なんだ' },
            {
                type: 'prompt', speaker: '山形', text: '空気の恩恵に感謝して<br>巫女さんが空気に向かって舞うよ',
                promptText: '空気の恩恵に感謝して<br>巫女さんが空気に向かって舞うよ',
                tsukkomi: [
                    { text: "いぱだだ祭りだな！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '青森「見えねものに向がって<br>舞うってなんだ！」' },
                    { text: "感謝の仕方<br>独特すぎる！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '青森「なんぼ空気が綺麗でも<br>崇め奉るのはやりすぎだ・・・」' },
                    { text: "ある意味<br>一番大事だな", 
                        point: 0, type: ['p'], 
                        reaction: '青森「確がに空気がねど<br>ラッセラーもしゃべれねもんな・・・」' },
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '青森', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '青森', text: 'ツッコミどごろが多いってごどは<br>わがった' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '青森', text: '・・・・・・' },
            { type: 'dialogue', speaker: '青森', text: 'それでいいのがよ！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 岩手 -----------------------------------------------------------------------------------------------------
    'iwate': {
        scenario: [
            { type: 'dialogue', speaker: '岩手', text: 'はいどうも〜！<br>岩手県で〜す！' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '岩手', text: '岩手といえばやっぱり「広さ」だね<br>本州で一番面積が広いんだ' },
            { type: 'dialogue', speaker: '岩手', text: '四国4県がすっぽり入るくらいの<br>スケール感が自慢だよ' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>そんなに大きいんだ' },
            { type: 'dialogue', speaker: '山形', text: 'それなら<br>あの大規模イベントも余裕だね' },
            { type: 'dialogue', speaker: '岩手', text: '大規模イベント？<br>ロックフェスとか？' },
            { type: 'dialogue', speaker: '山形', text: 'いや<br>「人間将棋」だよ' },
            { type: 'dialogue', speaker: '岩手', text: '・・・え？<br>人間将棋？なにそれ' },
            { type: 'dialogue', speaker: '山形', text: '広い土地があるなら<br>将棋盤を巨大化できるんじゃない？' },
            { type: 'dialogue', speaker: '岩手', text: '・・・将棋盤を巨大化！？' },
            { type: 'dialogue', speaker: '山形', text: '甲冑を着た人間が<br>巨大な盤の上を駒として練り歩くんだ' },
            {
                type: 'prompt', speaker: '山形', text: '山形ではお馴染みの<br>大規模イベントだよ',
                promptText: '甲冑を着た人間が<br>巨大な盤の上を駒として練り歩くんだ',
                tsukkomi: [
                    { text: "巨大化させた<br>だけじゃん！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '岩手「物理的にデカくして<br>どうするんだよ！」' },
                    { text: "土地の<br>無駄遣いだろ！", 
                        point: 1, type: ['t', 'p'], 
                        reaction: '岩手「もっと有効な<br>土地活用があるんじゃない！？」' },
                    { text: "めちゃくちゃ<br>時間かかりそう", 
                        point: 0, type: ['v'], 
                        reaction: '岩手「大きすぎて<br>日が暮れちゃうよ」' }
                ]
            },
            { type: 'dialogue', speaker: '岩手', text: 'はぁ…デカければいいってもんじゃないよ' },
            { type: 'dialogue', speaker: '岩手', text: '岩手は大きさだけじゃなくて<br>食のバリエーションも豊富なんだ' },
            { type: 'dialogue', speaker: '岩手', text: '「わんこそば」「盛岡冷麺」<br>「じゃじゃ麺」！' },
            { type: 'dialogue', speaker: '岩手', text: 'いわゆる「盛岡三大麺」だね' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>3種類もあるんだ' },
            { type: 'dialogue', speaker: '岩手', text: '山形さんも<br>ラーメン大好きって聞いてるけど' },
            { type: 'dialogue', speaker: '山形', text: '山形はラーメンと<br>そばがたくさんあるよ' },
            { type: 'dialogue', speaker: '山形', text: 'それにちなんで、山形県の<br>新しい名前ができたんだ' },
            { type: 'dialogue', speaker: '岩手', text: '新しい名前・・・？' },
            {
                type: 'prompt', speaker: '山形', text: '「ラーメン県そば王国やまがた」',
                tsukkomi: [
                    { text: "いろいろ<br>詰め込みすぎだろ！", 
                        point: 1, type: ['t', 'p'], 
                        reaction: '岩手「ラーメン！？そば！？<br>やまがた！？どれ！？」' },
                    { text: "なんで県の中に<br>王国があるんだよ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '岩手「住所どうなってんの！？<br>行政区分がめちゃくちゃすぎる！」' },
                    { text: "そこまで来たら<br>うどんも欲しい", 
                        point: 0, type: ['p','v'], 
                        reaction: '岩手「うどんにも力入れてみてよ」' }
                ]
            },
            { type: 'dialogue', speaker: '岩手', text: '岩手はもっとこう<br>ミステリアスな民話の世界が自慢だよ' },
            { type: 'dialogue', speaker: '岩手', text: '遠野市の「カッパ伝説」とかね' },
            { type: 'dialogue', speaker: '岩手', text: '観光協会に行くと<br>「カッパ捕獲許可証」がもらえるんだ' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>本格的だね' },
            { type: 'dialogue', speaker: '岩手', text: 'まあ<br>実際に捕まえた人はいないけど' },
            { type: 'dialogue', speaker: '岩手', text: 'でもその「本気度」が<br>ロマンチックでしょ？' },
            { type: 'dialogue', speaker: '山形', text: '確かに' },
            { type: 'dialogue', speaker: '山形', text: '山形には“ケサランパサラン”っていう<br>謎の生物がいるよ' },
            { type: 'dialogue', speaker: '岩手', text: 'あ、聞いたことある！<br>白い毛玉みたいなやつだよね？' },
            { type: 'dialogue', speaker: '山形', text: 'そうそう' },
            { type: 'dialogue', speaker: '山形', text: '動物か植物かも分からない<br>未確認生物なんだけど' },
            {
                type: 'prompt', speaker: '山形', text: 'コイツはよく捕獲されてて<br>水族館で普通に展示されてるよ',
                tsukkomi: [
                    { text: "どこに行けば<br>捕獲できるの？", 
                        point: 0, type: ['p'], 
                        reaction: '山形「特に庄内地域に<br>生息してるらしいよ」' },
                    { text: "なんで水族館で<br>展示してるんだよ！", 
                        point: 1, type: ['t','v'], 
                        reaction: '岩手「あの毛玉<br>海の生き物なの！？」' },
                    { text: "未確認生物<br>確認済みじゃん！", 
                        point: 3, type: ['t', 'p', 'v'],
                        reaction: '岩手「未確認生物リスト<br>更新しなきゃ！」' }
                    ]
            },

            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '岩手', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '岩手', text: 'ツッコミどころが多いってことは<br>わかった' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '岩手', text: '・・・・・・' },
            { type: 'dialogue', speaker: '岩手', text: 'それでいいのかよ！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 宮城 ---------------------------------------------------------------------------------------
    'miyagi': {
        scenario: [
            { type: 'dialogue', speaker: '宮城', text: 'はいどうもー！<br>宮城県でーす' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '宮城', text: '宮城といえば、やっぱり<br>「伊達政宗公」だよね' },
            { type: 'dialogue', speaker: '宮城', text: '独眼竜の三日月兜！<br>あのとことん粋でカッコいい生き様！' },
            { type: 'dialogue', speaker: '宮城', text: '仙台駅前にも騎馬像があるけど<br>まさに宮城のシンボルだよ' },
            { type: 'dialogue', speaker: '宮城', text: 'そしてその心を受け継いでるのが<br>観光PRキャラの「むすび丸」！' },
            { type: 'dialogue', speaker: '宮城', text: 'おにぎりの顔に、三日月の兜！<br>凛々しくて可愛いでしょ？' },
            { type: 'dialogue', speaker: '山形', text: '甲冑を着たキャラかぁ<br>強そうでいいね' },
            { type: 'dialogue', speaker: '山形', text: '山形にも地元を盛り上げてくれる<br>キャラクターがいるよ' },
            { type: 'dialogue', speaker: '宮城', text: 'おっ、政宗公の宿敵<br>最上義光公のキャラとか？' },
            { type: 'dialogue', speaker: '山形', text: 'いや<br>朝日町の「桃色ウサヒ」' },
            { type: 'dialogue', speaker: '宮城', text: '・・・桃色ウサヒ？' },
            { type: 'dialogue', speaker: '山形', text: 'ピンク色のウサギの着ぐるみで<br>無個性・無軌道・無表情' },
            {
                type: 'prompt', speaker: '山形', text: 'キャッチコピーは<br>「朝日が育んだ圧倒的無個性」だよ',
                promptText: '無個性・無軌道・無表情<br>「圧倒的無個性」なウサギだよ',
                tsukkomi: [
                    { text: "盛り上げる気<br>あんのか！？", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '宮城「超やる気なさそうじゃん！<br>むすび丸を見習え！」' },
                    { text: "逆に<br>哲学的だな", 
                        point: 0, type: ['p'], 
                        reaction: '宮城「無の境地ってこと・・・？」' },
                    { text: "山形<br>関係ないじゃん！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '宮城「ご当地キャラって<br>そんな感じでいいの！？」' }
                ]
            },
            { type: 'dialogue', speaker: '宮城', text: '宮城はもっとこう<br>王道のグルメで勝負するよ' },
            { type: 'dialogue', speaker: '宮城', text: 'やっぱり仙台名物「牛タン」だね！' },
            { type: 'dialogue', speaker: '宮城', text: '炭火で焼いた厚切りの牛タン・・・<br>これぞ宮城を代表する味だよ' },
            { type: 'dialogue', speaker: '山形', text: '牛タンは美味しいよね' },
            { type: 'dialogue', speaker: '山形', text: '山形名物なら<br>ラーメンとそばかな' },
            { type: 'dialogue', speaker: '宮城', text: '山形市って<br>ラーメン消費額日本一なんでしょ？' },
            { type: 'dialogue', speaker: '山形', text: 'そうだよ<br>ラーメン愛は県民の誇りなんだ' },
            { type: 'dialogue', speaker: '山形', text: 'だからそれをアピールするために<br>新しい名前ができたんだ' },
            { type: 'dialogue', speaker: '宮城', text: '・・・え？<br>新しい名前？' },
            { type: 'dialogue', speaker: '山形', text: '山形県改め・・・' },
            {
                type: 'prompt', speaker: '山形', text: '「ラーメン県そば王国やまがた」だよ',
                promptText: '山形県改め<br>「ラーメン県そば王国やまがた」だよ',
                tsukkomi: [
                    { text: "なんで県の中に<br>王国作ってるんだよ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '宮城「せめて逆だろ！<br>逆だとしても独立国家になってるし！」' },
                    { text: "いろいろ<br>詰め込みすぎだろ！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '宮城「キャッチコピーの割に<br>まとまり無いな！」' },
                    { text: "一度に両方<br>楽しめるね", 
                        point: 0, type: ['p'], 
                        reaction: '宮城「麺好きにはたまらない<br>パラダイスってことか・・・」' }
                ]
            },
            { type: 'dialogue', speaker: '宮城', text: '麺への執着心が怖いな・・・' },
            { type: 'dialogue', speaker: '宮城', text: '麺料理といえば、宮城は<br>「冷やし中華発祥の地」だからね！' },
            { type: 'dialogue', speaker: '宮城', text: '暑い夏に、冷たい麺をすする・・・<br>あのスタイルを作ったのは宮城なんだよ' },
            { type: 'dialogue', speaker: '山形', text: 'じゃあ宮城さんには<br>すごくお世話になってるんだなあ' },
            { type: 'dialogue', speaker: '山形', text: '「冷やし中華はじめました」<br>ってやつ、山形もやるよ' },
            { type: 'dialogue', speaker: '宮城', text: 'やっぱりそうだよね<br>夏といえば冷やし中華！' },
            { type: 'dialogue', speaker: '山形', text: 'あと<br>「冷やしラーメンはじめました」とか' },
            { type: 'dialogue', speaker: '宮城', text: 'やっぱり山形名物は<br>ラーメンだね' },
            {
                type: 'prompt', speaker: '山形', text: '「冷やしシャンプーはじめました」<br>ってのもあるよ',
                tsukkomi: [
                    { text: "変な方向に<br>派生してる！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '宮城「冷やし中華パロディ！？<br>ラーメンでギリでしょ・・・」' },
                    { text: "気持ち<br>よさそうだね", 
                        point: 0, type: ['p'], 
                        reaction: '宮城「やっぱり頭皮は<br>さっぱりさせたいよね」' },
                    { text: "なんでもかんでも<br>冷やしすぎだろ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '宮城「冷やし中華だけで<br>十分涼しげだろ！」' }
                ]
            },

            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '宮城', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '宮城', text: 'ツッコミどころが多いってことは<br>わかったよ' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '宮城', text: '・・・・・・' },
            { type: 'dialogue', speaker: '宮城', text: 'それでいいのかよ！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 秋田 ----------------------------------------------------------------------------------------------------
    'akita': {
        scenario: [
            { type: 'dialogue', speaker: '秋田', text: 'はいどうも〜！<br>秋田県だ〜！' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '秋田', text: '秋田と言えば、今や世界のアイドル<br>「秋田犬」がいるぞ！' },
            { type: 'dialogue', speaker: '秋田', text: 'ザギトワ選手もメロメロになった<br>あのモフモフ！国の天然記念物だ！' },
            { type: 'dialogue', speaker: '秋田', text: 'あの愛くるしい毛並みは<br>日本の宝だと言ったって過言ではねな' },
            { type: 'dialogue', speaker: '山形', text: '確かに<br>モフモフは癒やされるよね' },
            { type: 'dialogue', speaker: '山形', text: '山形にも<br>モフモフした生き物がいるよ' },
            { type: 'dialogue', speaker: '秋田', text: '山形にモフモフ？<br>なんの動物だ？' },
            { type: 'dialogue', speaker: '山形', text: '「ケサランパサラン」って知ってる？' },
            { type: 'dialogue', speaker: '秋田', text: 'ケサランパサラン・・・？<br>それ未確認生物じゃながった？' },
            { type: 'dialogue', speaker: '山形', text: 'そうそう' },
            { type: 'dialogue', speaker: '山形', text: '動物か植物かも分からない<br>未確認生物なんだけど' },
            {
                type: 'prompt', speaker: '山形', text: '水族館で展示されてるんだ',
                promptText: '未確認生物「ケサランパサラン」が<br>水族館で展示されてるんだ',
                tsukkomi: [
                    { text: "未確認生物を<br>大公開しねでけろ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '秋田「未確認じゃなくなるべ！<br>学者呼んでこい！」' },
                    { text: "秋田犬と<br>モフモフ勝負だな", 
                        point: 0, type: ['v'], 
                        reaction: '秋田「ケサランパサランは<br>懐かねべ」' },
                    { text: "なんで水族館に<br>展示するんだか！？", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '秋田「あれ魚の仲間だったんだが！？」' }
                ]
            },
            { type: 'dialogue', speaker: '秋田', text: 'ほんと、謎だらけの水族館だな・・・' },
            { type: 'dialogue', speaker: '秋田', text: '秋田はもっとこう<br>ド迫力のエンターテイメントが自慢だ！' },
            { type: 'dialogue', speaker: '秋田', text: '「大曲の花火」を知らねとは<br>言わせねよ！' },
            { type: 'dialogue', speaker: '秋田', text: '全国の花火師が腕を競い合う<br>日本最高峰の競技大会なんだ！' },
            { type: 'dialogue', speaker: '秋田', text: '夜空を埋め尽くす光のアート！<br>あれこそ世界一のスケールだべ' },
            { type: 'dialogue', speaker: '山形', text: 'きれいだよね〜' },
            { type: 'dialogue', speaker: '山形', text: '山形にも<br>とてつもなく大きいイベントがあるよ' },
            { type: 'dialogue', speaker: '秋田', text: 'ほう、山形にも<br>デカい花火大会があるんだか？' },
            { type: 'dialogue', speaker: '山形', text: 'いや<br>「日本一の芋煮会フェスティバル」だよ' },
            { type: 'dialogue', speaker: '秋田', text: '芋煮って<br>河原で鍋つっつくやつだよな？' },
            { type: 'dialogue', speaker: '秋田', text: 'なんで日本一なんだか？' },
            { type: 'dialogue', speaker: '山形', text: '日本一の芋煮会フェスティバル<br>では・・・' },
            {
                type: 'prompt', speaker: '山形', text: '直径6.5メートルの巨大鍋と<br>バックホーを使って作るんだ',
                tsukkomi: [
                    { text: "日本一って<br>大きさのことなんだか！？", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '秋田「もっと競うところあるよな！？」' },
                    { text: "工事現場みたいに<br>なってるよ！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '秋田「食べ物作るのに<br>重機使うんだか！？」' },
                    { text: "確かに<br>大きいイベントだな・・・", 
                        point: 0, type: ['p'], 
                        reaction: '秋田「サイズを大きくすれば<br>なんでも大規模になるもんな」' }
                ]
            },
            { type: 'dialogue', speaker: '秋田', text: '重機で料理は<br>ワイルド過ぎるよ・・・' },
            { type: 'dialogue', speaker: '秋田', text: 'やっぱ東北人は<br>神様への繊細な感謝の心が大事だ' },
            { type: 'dialogue', speaker: '秋田', text: '秋田の「竿燈まつり」を見てけろ！' },
            { type: 'dialogue', speaker: '秋田', text: '稲穂に見立てた提灯を<br>絶妙なバランスで操る' },
            { type: 'dialogue', speaker: '秋田', text: 'あの美しい光には<br>五穀豊穣への祈りが込められてるんだ' },
            { type: 'dialogue', speaker: '山形', text: '感謝の心は大事だよね' },
            { type: 'dialogue', speaker: '山形', text: '山形にも<br>感謝を伝えるお祭りがあるよ' },
            { type: 'dialogue', speaker: '秋田', text: 'おっ、わかってるな<br>なんていう祭りだか？' },
            { type: 'dialogue', speaker: '山形', text: '「空気まつり」だよ' },
            { type: 'dialogue', speaker: '秋田', text: '・・・空気まつり？' },
            { type: 'dialogue', speaker: '山形', text: '朝日町にある「空気神社」の<br>「空気まつり」' },
            { type: 'dialogue', speaker: '山形', text: '空気の恩恵に感謝して<br>有志によって建立された神社で' },
            {
                type: 'prompt', speaker: '山形', text: '空気の重要性を祝って<br>感謝するお祭りだよ',
                tsukkomi: [
                    { text: "どんな神社だよ！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '秋田「空気は山形だけのものじゃねべ！」' },
                    { text: "ある意味<br>一番大事だな", 
                        point: 0, type: ['p'], 
                        reaction: '秋田「東北の空気は綺麗だがらな<br>秋田も感謝しねと」' },
                        { text: "感謝の仕方<br>独特すぎる！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '秋田「空気も祀られて<br>困惑してるよ！」' },
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '秋田', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '秋田', text: 'ツッコミどころが多いってことは<br>わかった' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '秋田', text: '・・・・・・' },
            { type: 'dialogue', speaker: '秋田', text: 'それでいいのかよ！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 福島 -----------------------------------------------------------------------------------------------------
    'fukushima': {
        scenario: [
            { type: 'dialogue', speaker: '福島', text: 'はいどうもー！<br>福島県です〜' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '福島', text: '福島といえば日本三大ラーメンの一つ<br>「喜多方ラーメン」！' },
            { type: 'dialogue', speaker: '福島', text: '朝からラーメン食べる<br>「朝ラー」文化もあるしね' },
            { type: 'dialogue', speaker: '山形', text: '朝からラーメンかあ・・・<br>それもいいね' },
            { type: 'dialogue', speaker: '山形', text: '山形もラーメン大好きで<br>ラーメン消費額日本一なんだよ' },
            { type: 'dialogue', speaker: '山形', text: '山形ではラーメンは<br>最高のご馳走なんだ' },
            { type: 'dialogue', speaker: '福島', text: 'ご馳走？お祝い事があったら<br>ラーメン食べるとか？' },
            { type: 'dialogue', speaker: '山形', text: 'ううん、おもてなしだよ' },
            {
                type: 'prompt', speaker: '山形', text: '山形では来客があったら<br>ラーメンの出前をとるんだ',
                tsukkomi: [
                    { text: "ラーメンの階級<br>高すぎるだろ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '福島「県民みんなそのレベルで<br>ラーメン愛してんの！？」' },
                    { text: "おもてなしにしては<br>こってりしすぎだろ！", 
                        point: 1, type: ['v', 't'], 
                        reaction: '福島「もっとすぐ食べ終わるもの<br>出した方がいいだろ・・・」' },
                    { text: "ラーメン出てきたら<br>嬉しいね", 
                        point: 0, type: ['v'], 
                        reaction: '福島「最高の食べ物だからね」' }
                ]
            },
            { type: 'dialogue', speaker: '福島', text: 'ラーメン愛すごいな・・・' },
            { type: 'dialogue', speaker: '福島', text: '福島はもっとこう、ダイナミックな<br>祭りやイベントが自慢だよ' },
            { type: 'dialogue', speaker: '福島', text: '「わらじまつり」なんて<br>長さ12メートルの巨大わらじを担ぐんだ！' },
            { type: 'dialogue', speaker: '福島', text: 'どう？<br>このスケール感！' },
            { type: 'dialogue', speaker: '山形', text: '大きいのはいいことだね<br>山形にも大きいイベントがあるよ' },
            { type: 'dialogue', speaker: '福島', text: 'おっ、いいね<br>どんな？' },
            { type: 'dialogue', speaker: '山形', text: '直径6.5mの大鍋とバックホーで<br>3万食分の芋煮を作る' },
            { type: 'dialogue', speaker: '山形', text: '「日本一の芋煮会フェスティバル」<br>とか' },
            { type: 'dialogue', speaker: '福島', text: '確かに大きいな・・・' },
            { type: 'dialogue', speaker: '山形', text: '巨大な将棋盤の上を<br>人間が駒となって歩く' },
            {
                type: 'prompt', speaker: '山形', text: '「人間将棋」とかがあるよ',
                promptText: '日本一の芋煮会フェスティバルとか<br>人間将棋があるよ',
                tsukkomi: [
                    { text: "重機を<br>調理器具にすんな！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '福島「工事現場すぎるわ！」' },
                    { text: "なんでもかんでも<br>デカくしすぎだろ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '福島「こだわるところ<br>もっとあっただろ！」' },
                    { text: "迫力が<br>すごいね", 
                        point: 0, type: ['p'], 
                        reaction: '福島「でも巨大わらじの方が<br>鍋の直径より大きいよ」' }
                ]
            },
            { type: 'dialogue', speaker: '福島', text: 'やっぱり規格外だなぁ' },
            { type: 'dialogue', speaker: '福島', text: 'でも、めんこいものなら負けないよ' },
            { type: 'dialogue', speaker: '福島', text: '福島には「赤べこ」がいるからね' },
            { type: 'dialogue', speaker: '福島', text: 'あの首をゆらゆら振る姿は<br>見てるだけで癒やされるんだよ' },
            { type: 'dialogue', speaker: '福島', text: 'やっぱりマスコットは<br>めんこくないとね' },
            { type: 'dialogue', speaker: '山形', text: '赤べこは<br>ゆるくてかわいいよね' },
            { type: 'dialogue', speaker: '山形', text: '山形にも<br>脱力系のキャラクターがいるよ' },
            { type: 'dialogue', speaker: '福島', text: 'お、脱力系か！<br>どんなの？' },
            { type: 'dialogue', speaker: '山形', text: 'ウサギがモチーフの<br>「桃色ウサヒ」だよ' },
            { type: 'dialogue', speaker: '福島', text: 'へえ、ウサギかあ<br>めんこいキャラクターだね' },
            { type: 'dialogue', speaker: '山形', text: '朝日町の<br>非公式PRキャラクターなんだ' },
            { type: 'dialogue', speaker: '福島', text: 'え、非公式・・・？<br>まあ最近はそういうのも多いか' },
            { type: 'dialogue', speaker: '山形', text: '無個性・無軌道・無表情の<br>3拍子が揃った' },
            {
                type: 'prompt', speaker: '山形', text: '目が虚とした<br>無個性なキャラクターだよ',
                promptText: '無個性・無軌道・無表情<br>目が虚とした無個性なキャラクターだよ',
                tsukkomi: [
                    { text: "脱力系にも<br>程があるだろ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '福島「もっとやる気出せよ！<br>PRキャラクターなんだろ！？」' },
                    { text: "ゆるくて<br>めんこいね", 
                        point: 0, type: ['p'], 
                        reaction: '福島「みてるこっちまで<br>脱力しちまう」' },
                    { text: "“山形感”が<br>皆無！", 
                        point: 1, type: ['t', 'p'], 
                        reaction: '福島「もっと山形らしさ<br>出さないと！」' }
                ]
            },

            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '福島', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '福島', text: 'ツッコミどころが多いってことは<br>わかったよ' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '福島', text: '・・・・・・' },
            { type: 'dialogue', speaker: '福島', text: 'それでいいのかよ！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 群馬 ---------------------------------------------------------------------------------------------------------
    'gunma': {
        scenario: [
            { type: 'dialogue', speaker: '群馬', text: 'はいどうもー！<br>群馬県です！' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '群馬', text: '県の形を覚えるなら<br>群馬の右に出るものはいねえぜ' },
            { type: 'dialogue', speaker: '群馬', text: '俺たちには「<ruby>上毛<rt>じょうもう</rt></ruby>かるた」があるからな！' },
            { type: 'dialogue', speaker: '群馬', text: '「つ」は<br>「つる舞う形の群馬県！」' },
            { type: 'dialogue', speaker: '群馬', text: '県民全員が暗記している<br>最強のカードゲームなんさ！' },
            { type: 'dialogue', speaker: '山形', text: '県民全員が？<br>すごいね' },
            { type: 'dialogue', speaker: '山形', text: '頭脳スポーツなら<br>山形にも有名なのがあるよ' },
            { type: 'dialogue', speaker: '群馬', text: 'ほう、何かあるのか？<br>まさかトランプじゃねえべな' },
            { type: 'dialogue', speaker: '山形', text: 'ううん<br>「将棋」だよ' },
            { type: 'dialogue', speaker: '山形', text: '天童市は将棋の駒の生産量が<br>日本一だからね' },
            { type: 'dialogue', speaker: '群馬', text: '将棋か！<br>確かに立派な伝統文化だ' },
            { type: 'dialogue', speaker: '群馬', text: 'でも、カルタに比べると<br>おとなしいよな？' },
            { type: 'dialogue', speaker: '山形', text: '「人間将棋」っていう<br>BIGスケールな対局もやってるよ' },
            { type: 'dialogue', speaker: '群馬', text: '人間将棋・・・？' },
            {
                type: 'prompt', speaker: '山形', text: '巨大な将棋盤の上を<br>人間が駒になって歩くんだ',
                tsukkomi: [
                    { text: "時間が<br>かかりすぎる！！", 
                        point: 1, type: ['t','v'], 
                        reaction: '群馬「一局にどんだけかかる！？<br>日が暮れるべ！」' },
                    { text: "本当に“スケール”が<br>大きいのかよ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '群馬「将棋をそのまま<br>デカくしただけ！？」' },
                    { text: "上毛かるたも<br>そのサイズでやろうかな", 
                        point: 0, type: ['v'], 
                        reaction: '群馬「借り物競走みたいに<br>なりそう」' }
                ]
            },
            { type: 'dialogue', speaker: '群馬', text: '発想が突飛だな・・・' },
            { type: 'dialogue', speaker: '群馬', text: '俺たちは特産品のために<br>テーマパークを作ったんさ' },
            { type: 'dialogue', speaker: '群馬', text: 'こんにゃく芋生産量日本一！<br>その名も「こんにゃくパーク」だ！' },
            { type: 'dialogue', speaker: '群馬', text: '無料バイキングで行列ができる<br>最強のフードテーマパークだぜ' },
            { type: 'dialogue', speaker: '山形', text: 'あ、こんにゃくなら山形も好きだよ<br>「玉こんにゃく」' },
            { type: 'dialogue', speaker: '群馬', text: '玉こんにゃくか<br>群馬でもド定番だ' },
            { type: 'dialogue', speaker: '山形', text: 'そろそろ玉こんブームが来ても<br>いい頃だと思うんだ' },
            {
                type: 'prompt', speaker: '山形', text: 'インスタ映えする<br>「山形のタピオカ」として',
                promptText: '玉こんブームが来てもいい頃だと思うんだ<br>「山形のタピオカ」として',
                tsukkomi: [
                    { text: "確かに原材料<br>芋だけど！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '群馬「ちょっと無理矢理すぎねえか・・・？」' },
                    { text: "流行語大賞<br>狙うぞ！", 
                        point: 0, type: ['p', 'v'], 
                        reaction: '群馬「2人で玉こんにゃくを<br>流行らせよう！」' },
                    { text: "映えないわ！", 
                        point: 1, type: ['p','t'], 
                        reaction: '群馬「カラフルにしたら<br>ワンチャンあるかもだけど・・・」' }
                ]
            },
            { type: 'dialogue', speaker: '群馬', text: '・・・もっとこう<br>王道の可愛さはねえのか？' },
            { type: 'dialogue', speaker: '群馬', text: '群馬には「ぐんまちゃん」がいる！<br>ゆるキャラグランプリ王者だぞ！' },
            { type: 'dialogue', speaker: '群馬', text: 'この愛くるしい見た目！<br>知名度も抜群だ！' },
            { type: 'dialogue', speaker: '山形', text: '可愛いねぇ' },
            { type: 'dialogue', speaker: '山形', text: '可愛いキャラなら<br>朝日町の「桃色ウサヒ」がいるよ' },
            { type: 'dialogue', speaker: '群馬', text: 'ほう、ウサギか<br>さぞかし可愛いんだんべな？' },
            { type: 'dialogue', speaker: '山形', text: '無個性・無軌道・無表情<br>特徴がないピンク色のウサギの着ぐるみ' },
            { type: 'dialogue', speaker: '群馬', text: '着ぐるみ・・・？<br>それ言っていいのか？' },
            {
                type: 'prompt', speaker: '山形', text: 'キャッチフレーズは<br>「朝日が育んだ圧倒的無個性」',
                tsukkomi: [
                    { text: "そいつ本当に<br>人気か・・・？", 
                        point: 1, type: ['p', 'v'], 
                        reaction: '群馬「ゆるキャラグランプリを<br>なめるな！」' },
                    { text: "個性が無いのも<br>個性だよ", 
                        point: 0, type: ['p'], 
                        reaction: '群馬「尖ってて<br>いいんじゃないか？」' },
                    { text: "ご当地キャラが無個性で<br>いいのかよ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '群馬「地元をもっと<br>アピールしろよ！」' }
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '群馬', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '群馬', text: 'ツッコミどころが多いってことは<br>わかった' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '群馬', text: '・・・・・・' },
            { type: 'dialogue', speaker: '群馬', text: 'それでいいのかよ！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 東京 -----------------------------------------------------------------------------------------------------
    'tokyo': {
        scenario: [
            { type: 'dialogue', speaker: '東京', text: 'はいどうもー！<br>東京都と〜' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '東京', text: 'いや〜、東京は土地が狭くて<br>窮屈ですね' },
            { type: 'dialogue', speaker: '山形', text: '東京は人が多いからなあ' },
            { type: 'dialogue', speaker: '東京', text: '山形は広そうですね' },
            { type: 'dialogue', speaker: '山形', text: '山形は大きいから<br>いろんな大きいイベントが開催されるよ' },
            { type: 'dialogue', speaker: '山形', text: 'たとえば、将棋のイベントとか' },
            { type: 'dialogue', speaker: '東京', text: 'おっ、いいですね<br>何万人も集まる世界大会とかですか？' },
            { type: 'dialogue', speaker: '山形', text: 'いや<br>“人間将棋”って言って' },
            { type: 'dialogue', speaker: '山形', text: '将棋盤を巨大にして、<br>人間を「駒」として配置するんだ' },
            { type: 'dialogue', speaker: '東京', text: '・・・はい？' },
            {
                type: 'prompt', speaker: '山形', text: '甲冑を着た人間が<br>巨大な盤の上を練り歩くんだよ',
                tsukkomi: [
                    { text: "将棋を巨大に<br>しただけじゃないですか！", 
                        point: 3, 
                        type: ['t', 'p','v'],
                        reaction: '東京「物理的にデカくして<br>どうすんですか！」' },
                    { text: "土地の<br>無駄遣いですね", 
                        point: 1, 
                        type: ['t','v'],
                        reaction: '東京「そのスペースあれば<br>タワマン建ちますよ」' },
                    { text: "巨人用の<br>将棋かな？", 
                        point: 0, 
                        type: ['v'],
                        reaction: '東京「空から見るんですかね」' }
                ]
            },
            { type: 'dialogue', speaker: '東京', text: 'まったく...' },
            { type: 'dialogue', speaker: '東京', text: 'もっとこう、東京みたいに<br>“映える”ものはないんですか？' },
            { type: 'dialogue', speaker: '東京', text: '若者が行列を作るような、<br>オシャレな流行りものとか' },
            { type: 'dialogue', speaker: '山形', text: 'あるよ<br>“山形のタピオカ”が' },
            { type: 'dialogue', speaker: '東京', text: 'へぇ！ あるんですね！<br>じゃあ一つお願いします' },
            { type: 'dialogue', speaker: '東京', text: '・・・ってこれ、割り箸に刺さった<br>“玉こんにゃく”ですよね？' },
            {
                type: 'prompt', speaker: '山形', text: '黒くて丸くてモチモチしてるから<br>実質タピオカだよ',
                tsukkomi: [
                    { text: "確かに原材料は<br>芋だけど！", 
                        point: 3, 
                        type: ['t', 'p', 'v'],
                        reaction: '東京「植物学的な分類で<br>ゴリ押ししないでくださいよ！」' },
                    { text: "醤油の匂い<br>すごい", 
                        point: 0, 
                        type: ['v'],
                        reaction: '東京「美味しそう<br>流行るんじゃないですか？」' },
                    { text: "全然<br>映えないよ！", 
                        point: 1, 
                        type: ['p',"v"],
                        reaction: '東京「渋すぎでしょ！<br>原宿で持ってたら浮きますよ！」' }
                ]
            },
            { type: 'dialogue', speaker: '東京', text: 'タピオカだと思って食べたら・・・<br>出汁が染みてて美味しいですけど' },
            { type: 'dialogue', speaker: '東京', text: 'こんにゃくがこれだけ美味しいなら<br>鍋料理とかも絶品なんじゃないですか？' },
            { type: 'dialogue', speaker: '山形', text: 'おっ、鋭いね<br>山形といえば「芋煮」だよ' },
            { type: 'dialogue', speaker: '東京', text: 'やっぱり！' },
            { type: 'dialogue', speaker: '東京', text: 'みんなで鍋を囲んで温まるのって<br>最高ですよね' },
            { type: 'dialogue', speaker: '山形', text: '毎年、日本一の芋煮会をやってるよ' },
            { type: 'dialogue', speaker: '東京', text: '日本一の芋煮会？<br>最高の食材を使ってるんですか？' },
            { type: 'dialogue', speaker: '山形', text: 'いや<br>日本一の規模の芋煮会なんだ' },
            {
                type: 'prompt', speaker: '山形', text: '直径6.5mの鍋で作って<br>バックホーでかき混ぜるんだよ',
                tsukkomi: [
                    { text: "給食<br>センターかな", 
                        point: 1, 
                        type: ['t', 'v'],
                        reaction: '東京「何人分作る気ですか・・・」' },
                    { text: "調理器具が<br>おかしい！", 
                        point: 0, 
                        type: ['v', 'p'],
                        reaction: '東京「出汁じゃなくて鉄の味がしそうですね」' },
                    { text: "日本一の<br>“大きさ”なの！？", 
                        point: 3, 
                        type: ['p'],
                        reaction: '東京「デカけりゃいいってもんですか！？」' }
                ]
            },

            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '東京', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '東京', text: 'ツッコミどころが多いということは<br>よくわかりました' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '東京', text: '・・・・・・' },
            { type: 'dialogue', speaker: '東京', text: 'それでいいんですか！？' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 新潟 --------------------------------------------------------------------------------------------------------
    'niigata': {
        scenario: [
            { type: 'dialogue', speaker: '新潟', text: 'はいどうも〜！<br>新潟県と〜' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '新潟', text: 'このあいだ<br>長岡花火見に行ったんだよ' },
            { type: 'dialogue', speaker: '新潟', text: '復興祈願花火「フェニックス」<br>涙が出るほど綺麗だったなぁ' },
            { type: 'dialogue', speaker: '新潟', text: 'やっぱ日本海の夏といえば<br>長岡の大花火だよな' },
            { type: 'dialogue', speaker: '新潟', text: '山形にはなんかある？' },
            { type: 'dialogue', speaker: '山形', text: '山形の夏といえば・・・' },
            {
                type: 'prompt', speaker: '山形', text: '冷やしラーメン、冷やしシャンプー<br>・・・あとは冷やしマスクとか？',
                tsukkomi: [
                    { text: "冷やしシャンプー！？<br>風邪ひくだろ！", 
                        point: 1, 
                        type: ['p', 'v'], 
                        reaction: '新潟「冬の寒さで<br>冷たさは十分だろ...」' },
                    { text: "なんでもかんでも<br>冷やしすぎだろ！", 
                        point: 3, 
                        type: ['t', 'p','v'],
                        reaction: '新潟「雪国なんだから<br>夏くらい温まれよ！」' },
                    { text: "冷やしラーメン<br>美味そうだなぁ", 
                        point: 0, 
                        type: ['v'], 
                        reaction: '新潟「へぎそばも美味いけど<br>ラーメンもいいな...」' }
                ]
            },
            { type: 'dialogue', speaker: '新潟', text: '体冷やしてばっかりじゃダメだって' },
            { type: 'dialogue', speaker: '新潟', text: '秋になると<br>温かいご飯が恋しくなるだろ？' },
            { type: 'dialogue', speaker: '新潟', text: '新潟は魚沼産コシヒカリの<br>新米シーズン！' },
            { type: 'dialogue', speaker: '新潟', text: 'ピカピカの塩むすびなんて<br>新米シーズン！' },
            { type: 'dialogue', speaker: '新潟', text: 'コシヒカリの塩むすび<br>最高のご馳走だぞ' },
            { type: 'dialogue', speaker: '新潟', text: '山形は秋、何食べるの？<br>つや姫？ 雪若丸？' },
            { type: 'dialogue', speaker: '山形', text: '秋か〜' },
            { type: 'dialogue', speaker: '山形', text: '秋なら芋煮会かな<br>日本一の芋煮会をするんだよ' },
            { type: 'dialogue', speaker: '新潟', text: '日本一の芋煮会？<br>それは日本一美味しいってこと？' },
            {
                type: 'prompt', speaker: '山形', text: '直径6.5mの大鍋と、重機で作る<br>日本一の芋煮会フェスティバルだよ',
                tsukkomi: [
                    { text: "日本一って<br>デカさの話かよ！", 
                        point: 3, 
                        type: ['t', 'p','v'],
                        reaction: '山形「いいだろ別に<br>デカさでも」' },
                    { text: "重機！？<br>食べ物なのに！？", 
                        point: 1, 
                        type: ['p'],
                        reaction: '新潟「・・・まあ流石に<br>綺麗なの使ってるだろうけど」' },
                    { text: "柿の種<br>入れたら美味そう", 
                        point: 0, 
                        type: ['p', 'v'],
                        reaction: '山形「あ、食感のアクセントに<br>なるかもね」' }
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'フェスティバルと言えば・・・' },
            { type: 'dialogue', speaker: '新潟', text: 'え？<br>まだなんかあんの？'},
            { type: 'dialogue', speaker: '山形', text: 'うん<br>空気まつり' },
            { type: 'dialogue', speaker: '新潟', text: '・・・<br>空気まつり・・・？'},
            { type: 'dialogue', speaker: '山形', text: '空気神社のまつりだよ' },
            { type: 'dialogue', speaker: '新潟', text: '空気神社・・・？'},
            { type: 'dialogue', speaker: '山形', text: '空気の恩恵に感謝して<br>有志によってつくられた神社だよ' },
            { type: 'dialogue', speaker: '山形', text: 'やっぱ空気には<br>感謝しないと' },
            {
                type: 'prompt', speaker: '新潟', text: '空気に・・・感謝・・・？',
                promptText: '空気の恩恵に感謝して<br>有志によってつくられた神社だよ',
                tsukkomi: [
                    { text: "山形県民は<br>心が綺麗だなあ", 
                        point: 0, 
                        type: ['v'],
                        reaction: '新潟「感動したわ」' },
                    { text: "なんでそれで<br>神社になるんだよ！", 
                        point: 3, 
                        type: ['t', 'p','v'],
                        reaction: '新潟「発想と行動力が<br>突飛すぎるだろ...」' },
                    { text: "空気の神様って<br>なんだよ！", 
                        point: 1, 
                        type: ['v', 'p'],
                        reaction: '山形「いやいや<br>空気神社に神様いないから」' }
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '新潟', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '新潟', text: 'ツッコミどころが多いってことは<br>わかった' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '新潟', text: '・・・・・・' },
            { type: 'dialogue', speaker: '新潟', text: 'それでいいのかよ！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },

                ]

    },

    // -------- 長野 --------------------------------------------------------------------------------------------------------
    'nagano': {
        scenario: [
            { type: 'dialogue', speaker: '長野', text: 'どうも、長野県です' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '長野', text: 'さあ<br>ずく出していきましょう' },
            { type: 'dialogue', speaker: '長野', text: '長野といえば<br>やはり「信州そば」だね' },
            { type: 'dialogue', speaker: '長野', text: '戸隠、開田、更科…<br>地域ごとに歴史と格式があるんだ' },
            { type: 'dialogue', speaker: '長野', text: 'イチオシは「戸隠そば」！' },
            { type: 'dialogue', speaker: '長野', text: '日本三大そばの一つに数えられる<br>名門だよ' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>麺文化かぁ' },
            { type: 'dialogue', speaker: '山形', text: '山形では<br>ラーメンとそばが人気だよ' },
            { type: 'dialogue', speaker: '長野', text: 'ほう、山形も麺を食べるのか<br>でもそばへのこだわりは負けないよ' },
            { type: 'dialogue', speaker: '山形', text: '山形はラーメン消費額も日本一だし' },
            { type: 'dialogue', speaker: '山形', text: 'そば屋でラーメンが出るくらい<br>麺だらけだよ' },
            { type: 'dialogue', speaker: '山形', text: 'それで最近、山形県の<br>新しい名前ができたんだ' },
            { type: 'dialogue', speaker: '長野', text: '新しい名前・・・？<br>「信州」のようなブランド名かい？' },
            { type: 'dialogue', speaker: '山形', text: '山形県改め・・・' },
            {
                type: 'prompt', speaker: '山形', text: '「ラーメン県そば王国やまがた」だよ',
                tsukkomi: [
                    { text: "麺類が渋滞<br>しすぎだろ！", 
                        point: 1, type: ['t', 'p'], 
                        reaction: '長野「ラーメン！？そば！？<br>どっちがメインなんだよ！」' },
                    { text: "行政区分<br>どうなってんだ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '長野「県の中に王国建国してる！<br>二重行政にも程があるだろ！」' },
                    { text: "うどんもあれば<br>完璧だった", 
                        point: 0, type: ['v'], 
                        reaction: '長野「ラーン県うどん市<br>そば王国とか」' }
                ]
            },
            { type: 'dialogue', speaker: '長野', text: 'もっとこう<br>洗練された涼しい話題はないのかい？' },
            { type: 'dialogue', speaker: '長野', text: '長野には「軽井沢」という<br>世界的な避暑地があるよ' },
            { type: 'dialogue', speaker: '長野', text: '高原の爽やかな風と、木漏れ日・・・<br>これぞ「涼」を楽しむ大人の文化さ' },
            { type: 'dialogue', speaker: '山形', text: 'あ〜<br>涼しいのは大事だよね' },
            { type: 'dialogue', speaker: '山形', text: '山形の夏は暑いから<br>軽井沢行きたいな' },
            { type: 'dialogue', speaker: '長野', text: '何か暑さ対策<br>してないのかい？' },
            { type: 'dialogue', speaker: '山形', text: '「冷やし中華始めました」とか' },
            { type: 'dialogue', speaker: '長野', text: '・・・<br>ラーメン県そば王国だからね' },
            {
                type: 'prompt', speaker: '山形', text: '“冷やしラーメン”と“冷やしシャンプー”<br>も始まるね',
                tsukkomi: [
                    { text: "片っ端から<br>冷やしてる！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '長野「なんでもかんでも<br>冷やせばいいと思ってるだろ！」' },
                    { text: "山形県民は<br>暑がりなんだね", 
                        point: 0, type: ['p'], 
                        reaction: '長野「夏は軽井沢に<br>来るといいよ」' },
                    { text: "知覚過敏に<br>なるだろ！", 
                        point: 1, type:  ['v', 'p'], 
                        reaction: '長野「冷やしすぎるのも<br>良くないんじゃ・・・」' }
                ]
            },
            { type: 'dialogue', speaker: '長野', text: '頭を冷やすのもいいけど…' },
            { type: 'dialogue', speaker: '長野', text: 'もっとこう魂が熱くなるような<br>イベントはないのかい？' },
            { type: 'dialogue', speaker: '長野', text: '長野には<br>「<ruby>御柱<rt>おんばしら</rt></ruby>祭」があるよ<br>' },
            { type: 'dialogue', speaker: '長野', text: '巨大な丸太に乗って<br>急な坂を滑り落ちるんだ' },
            { type: 'dialogue', speaker: '長野', text: '死傷者が出ることもある<br>まさに命がけの男たちの祭りさ' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>ワイルドだね' },
            { type: 'dialogue', speaker: '山形', text: 'あ、そういえば山形にも<br>まつりがあるよ' },
            { type: 'dialogue', speaker: '長野', text: 'ほう、やはり勇壮な神輿や<br>厳格な儀式があるのかい？' },
            { type: 'dialogue', speaker: '山形', text: '「空気まつり」っていうんだ' },
            { type: 'dialogue', speaker: '長野', text: '・・・<br>空気まつり・・・？' },
            { type: 'dialogue', speaker: '山形', text: '空気神社のまつりだよ' },
            { type: 'dialogue', speaker: '長野', text: '空気神社・・・？<br>どこの神話の神様だい？' },
            { type: 'dialogue', speaker: '山形', text: '神話でも神様でもない<br>“空気”だよ' },
            { type: 'dialogue', speaker: '長野', text: 'え・・・？' },
            {
                type: 'prompt', speaker: '山形', text: '空気の恩恵に感謝して<br>有志によって建立された神社さ',
                tsukkomi: [
                    { text: "建造の動機が<br>フワッとしてる！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '長野「空気だけに！<br>・・・歴史的背景とかないのかよ！」' },
                    { text: "神様がいないのに<br>神社！？", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '長野「そんなのアリ！？」' },
                    { text: "環境意識が<br>高くて素敵だね", 
                        point: 0, type: ['p'], 
                        reaction: '長野「SDGsの先駆けだね<br>見習いたいよ」' } 
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '長野', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '長野', text: 'ツッコミどころが多いってことは<br>わかったよ' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '長野', text: '・・・・・・' },
            { type: 'dialogue', speaker: '長野', text: 'それでいいのかよ！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 京都 --------------------------------------------------------------------------------------------------------
    'kyoto': {
        scenario: [
            { type: 'dialogue', speaker: '京都', text: 'どうも<br>京都府です〜' }, 
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '京都', text: '形のＰＲ？<br>田舎はのどかでよろしいなぁ' },
            { type: 'dialogue', speaker: '京都', text: 'ウチらはそんなことせんでも<br>黙ってても人が集まってくるしなぁ' },
            { type: 'dialogue', speaker: '京都', text: 'なんせ「<ruby>千<rt>せん</rt></ruby>の<ruby>都<rt>みやこ</rt></ruby>」やから<br>石ころ一つでも観光名所になるんえ' },
            { type: 'dialogue', speaker: '京都', text: '野菜でもお菓子でも<br>「京都」って書いとけば高級に見えるもんや' },
            { type: 'dialogue', speaker: '京都', text: 'これが「<ruby>都<rt>みやこ</rt></ruby>」の品格やね' },
            { type: 'dialogue', speaker: '山形', text: 'そのブランド力は羨ましいなぁ' },
            { type: 'dialogue', speaker: '山形', text: '山形も負けないように<br>最強の武器をアピールすることにしたんだ' },
            { type: 'dialogue', speaker: '京都', text: 'へえ、京都に対抗できる武器なんか<br>なんかあるんか？' },
            { type: 'dialogue', speaker: '山形', text: '消費額日本一の「ラーメン」と<br>名物の「蕎麦」だよ' },
            { type: 'dialogue', speaker: '山形', text: 'だから、みんなに知ってもらえるように<br>思い切って改名したんだ' },
            { type: 'dialogue', speaker: '京都', text: '改名？「麺処」とか？<br>・・・まさか「ラーメン県」やないやろな？' },
            { type: 'dialogue', speaker: '山形', text: '山形県改め・・・' },
            {
                type: 'prompt', speaker: '山形', text: '「ラーメン県そば王国やまがた」だよ',
                tsukkomi: [
                    { text: "名前<br>長すぎるわ！", 
                        point: 1, type: ['t', 'p'], 
                        reaction: '京都「宛名書きで<br><ruby>腱鞘炎<rt>けんしょうえん</rt></ruby>になるわ！」' },
                    { text: "県の中に<br>王国があるん！？", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '京都「謀反か！？<br><ruby>帝<rt>みかど</rt></ruby>も呆れてはるで！」' }, 
                    { text: "素直で<br>よろしいなぁ", 
                        point: 0, type: ['v'], 
                        reaction: '京都「飾り気のない名前…<br>田舎の人は元気やねぇ」' }
                ]
            },
            { type: 'dialogue', speaker: '京都', text: 'ラーメンにそばて・・・<br>炭水化物ばっかりやないか' },
            { type: 'dialogue', speaker: '京都', text: 'やっぱ日本人は「心」が大事やで' },
            { type: 'dialogue', speaker: '京都', text: '京都は歩けば「神社」に当たるくらい<br>由緒正しい神様仏様がおんねん' },
            { type: 'dialogue', speaker: '京都', text: '金閣寺に銀閣寺・・・<br>華やかさが違うやろ？' },
            { type: 'dialogue', speaker: '山形', text: '神社なら山形にも<br>ひと味違ったのがあるよ' },
            { type: 'dialogue', speaker: '京都', text: '松尾芭蕉も詠んだ「<ruby>立石寺<rt>りっしゃくじ</rt></ruby>」とか<br>修験道の聖地「<ruby>出羽三山<rt>でわさんざん</rt></ruby>」やろ？' },
            { type: 'dialogue', speaker: '京都', text: 'あれはなかなか風情があってよろしいなぁ' },
            { type: 'dialogue', speaker: '山形', text: '「空気神社」だよ' },
            { type: 'dialogue', speaker: '京都', text: '・・・・・・<br>空気神社？' },
            {
                type: 'prompt', speaker: '山形', text: '空気の恩恵に感謝して作られた<br>空気がご神体の神社だよ',
                tsukkomi: [
                    { text: "賽銭箱<br>置いてるん？", 
                        point: 1, type: ['t', 'v'], 
                        reaction: '京都「維持費かからなそうで<br>よろしいな！」' }, 
                    { text: "心が<br>洗われそうやな・・・", 
                        point: 0, type: ['v'], 
                        reaction: '京都「まあ・・・<br>汚れた心には効くかもしれんな」' },
                        { text: "どんな感謝の<br>仕方やねん！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '京都「空気はんもまさか自分が<br>ご神体になるとは思わんかったやろ・・・」' }
                ]
            },
            { type: 'dialogue', speaker: '京都', text: '実体がないもんを拝むとは・・・<br>掴みどころがないなぁ' },
            { type: 'dialogue', speaker: '京都', text: '京都は「おもてなし」ひとつとっても<br>ちゃんと意味を持たせるで' },
            { type: 'dialogue', speaker: '京都', text: '来客に「ぶぶ漬け」を出したら<br>「早よ帰ってや」のサインやったりな' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜、裏があるんだね' },
            { type: 'dialogue', speaker: '山形', text: '山形のおもてなしでは<br>素直に「ご馳走」を出すよ' },
            { type: 'dialogue', speaker: '京都', text: 'ほう、自信満々やな<br>ほな、その「ご馳走」とやらを出してみぃ' },
            {
                type: 'prompt', speaker: '山形', text: 'お客さんが来たら<br>ラーメンの出前を取るよ',
                tsukkomi: [
                    { text: "ラーメン<br>好きすぎやろ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '京都「全人類ラーメン好きやと思っとるん！？<br>頭の中、麺で埋まっとるんか！」' },
                    { text: "そばは<br>出さんの？", 
                        point: 0, type: ['v'], 
                        reaction: '京都「そば王国なんやろ？<br>忘れんといてや」' },
                    { text: "カロリー<br>高すぎやろ！", 
                        point: 1, type: ['t', 'p'], 
                        reaction: '京都「来客のたびにそれなん！？<br>重すぎるわぁ・・・」' }
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '京都', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '京都', text: 'ツッコミどころが多いってことは<br>ようわかったわ' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '京都', text: '・・・・・・' },
            { type: 'dialogue', speaker: '京都', text: 'それでええのんか！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 大阪 -----------------------------------------------------------------------------------------------------
    'osaka': {
        scenario: [
            { type: 'dialogue', speaker: '大阪', text: 'はいどうもー！！<br>大阪府でーす！！ 元気ですかー！！' },
            { type: 'dialogue', speaker: '山形', text: '・・・・・・' },
            { type: 'dialogue', speaker: '大阪', text: '...って、喋らんのかい！！<br>放送事故や！！' },
            { type: 'dialogue', speaker: '山形', text: 'あ、ごめん<br>今、空気と一体化してた' },
            { type: 'dialogue', speaker: '大阪', text: '一体化て何やねん！<br>怖いわ！！' },
            { type: 'dialogue', speaker: '山形', text: '山形県民は空気を崇拝してるからね' },
            { type: 'dialogue', speaker: '大阪', text: '崇拝て！<br>空気拝んでどうすんねん！' },
            { type: 'dialogue', speaker: '大阪', text: 'ビリケンさんみたいに<br>足の裏撫でたら儲かるとかあるん？' },
            { type: 'dialogue', speaker: '山形', text: 'ご利益があるかは<br>わからないけど・・・' },
            { type: 'dialogue', speaker: '山形', text: '「空気神社」はあるよ' },
            { type: 'dialogue', speaker: '大阪', text: '空気神社！？<br>嘘みたいな名前やな！' },
            { type: 'dialogue', speaker: '山形', text: '本殿もなくて、<br>5m四方の「鏡」があるだけ' },
            { type: 'prompt', speaker: '山形', text: 'ただ、<br>そこに映る空気に感謝するんだ・・・' ,
                promptText: '本殿もなくて、5mの「鏡」があるだけ<br>ただ、そこに映る空気に感謝するんだ...',
                tsukkomi: [
                    { text: "感謝はわかるけど<br>なんで神社建ててん！", 
                        point: 3, 
                        type: ['t', 'p','v'],
                        reaction: '大阪「発想が飛躍しすぎや！<br>深呼吸しとけばええやろ！」' },
                    { text: "通天閣のほうが<br>ご利益あるわ！", 
                        point: 1, 
                        type: ['p', 'v'],
                        reaction: '大阪「ビリケンさんは黄金やぞ！」' },
                    { text: "吸い溜めして<br>持って帰ったろか！", 
                        point: 0, 
                        type: ['v'],
                        reaction: '大阪「タダのもんは限界まで貰わな損や！」' }
                ]
            },
            { type: 'dialogue', speaker: '大阪', text: 'もうええ！ <br>神社はわかった！' },
            { type: 'dialogue', speaker: '大阪', text: 'もっとこう<br>派手で面白いヤツおらんのか！！' },
            { type: 'dialogue', speaker: '大阪', text: 'くいだおれ太郎とか<br>グリコとか！' },
            { type: 'dialogue', speaker: '山形', text: '道頓堀の看板とか<br>おばちゃんのヒョウ柄みたいな' },
            { type: 'dialogue', speaker: '山形', text: 'インパクトあるやつ頼むで！' },
            { type: 'dialogue', speaker: '山形', text: 'それならピンク色のウサギの<br>「桃色ウサヒ」がいるよ' },
            { type: 'dialogue', speaker: '山形', text: '朝日町の<br>非公式PRキャラクターなんだ' },
            { type: 'dialogue', speaker: '大阪', text: 'ピンク！ ええやん！<brド派手で人気者なんやろな？' },
            { type: 'dialogue', speaker: '山形', text: '目は虚ろで光がない<br>通称「備品」' },
            { type: 'dialogue', speaker: '山形', text: '無個性・無軌道・無表情の<br>三拍子が揃った' },
            { type: 'dialogue', speaker: '山形', text: '特徴がない<br>ピンク色のウサギの着ぐるみだよ' },
            { type: 'dialogue', speaker: '大阪', text: 'アカンやん！！<br>三拍子そろってアカンやん！！' },
            {
                type: 'prompt', speaker: '山形', text: 'でも儲け話は大好きなんだ<br>中の人の存在も隠さないしね',
                tsukkomi: [
                    { text: "夢を<br>壊すなや！", 
                        point: 3, 
                        type: ['t', 'p','v'],
                        reaction: '大阪「子供が泣くわ！<br>夢の国を見習えや！」' },
                    { text: "くいだおれ太郎<br>見習えや！", 
                        point: 1, 
                        type: ['v', 'p'],
                        reaction: '大阪「人形ですらもっと働くで！」' },
                    { text: "カネの匂いが<br>プンプンするわ！", 
                        point: 0, 
                        type: ['v'],
                        reaction: '大阪「そこだけ大阪と<br>気が合いそうやな！」' }
                ]
            },
            { type: 'dialogue', speaker: '大阪', text: 'キャラ濃いわー！<br>胃もたれするわ！' },
            { type: 'dialogue', speaker: '大阪', text: 'もっと胃に優しいもん無いん？' },
            { type: 'dialogue', speaker: '山形', text: 'じゃあ「芋煮」食べる？' },
            { type: 'dialogue', speaker: '山形', text: '芋煮会フェスティバルでは<br>3万人分の芋煮を作るよ' },
            { type: 'dialogue', speaker: '大阪', text: '3万人！？商売繁盛やな！<br>鍋なんぼほど並べる気や！' },
            { type: 'dialogue', speaker: '山形', text: 'ううん、鍋は1つだよ' },
            { type: 'dialogue', speaker: '大阪', text: '...は？ 1つ？' },
            {
                type: 'prompt', speaker: '山形', text: '直径6.5mの鍋と重機で作る<br>大規模な芋煮会だよ',
                tsukkomi: [
                    { text: "なんで鍋ごと<br>デカくしてん！", 
                        point: 3, 
                        type: ['t','p','v'],
                        reaction: '大阪「一気に3万食作るんかい！」' }, 
                    { text: "隠し味が<br>「鉄分」になるわ！", 
                        point: 1, 
                        type: ['v'],
                        reaction: '大阪「貧血には<br>ええかもしれんけど！」' },
                    { text: "重機で<br>「あ〜ん」して！", 
                        point: 0, 
                        type: ['v', 'p'],
                        reaction: '大阪「って口裂けるわ！<br>アームでかすぎんねん！」' }
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '大阪', text: 'せやなぁ<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '大阪', text: 'ツッコミどころが多すぎる<br>ってことはようわかったわ' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '大阪', text: '・・・・・・' },
            { type: 'dialogue', speaker: '大阪', text: 'ほんまにそれでええんかい！！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！！' },
        ]
    },

    // -------- 兵庫 ---------------------------------------------------------------------------------------------------------
    'hyogo': {
        scenario: [
            { type: 'dialogue', speaker: '兵庫', text: 'はいどうもー！<br>兵庫県です！' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '兵庫', text: '兵庫といえば<br>北は日本海、南は瀬戸内海！' },
            { type: 'dialogue', speaker: '兵庫', text: '「日本の縮図」って言われるほど<br>多様なんや' },
            { type: 'dialogue', speaker: '兵庫', text: '海水浴もスキーも温泉も<br>県内だけで全部完結する完璧な県やで' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>いろんな要素が詰まってるんだね' },
            { type: 'dialogue', speaker: '山形', text: '山形も、いろんな要素を詰め込んで<br>新しい名前を作ったよ' },
            { type: 'dialogue', speaker: '兵庫', text: 'ほう、兵庫みたいに<br>かっこいいキャッチコピーか？' },
            { type: 'dialogue', speaker: '山形', text: '山形県改め・・・' },
            {
                type: 'prompt', speaker: '山形', text: '「ラーメン県そば王国やまがた」だよ',
                tsukkomi: [
                    { text: "詰め込み<br>すぎやろ！", 
                        point: 1, type: ['t', 'p'], 
                        reaction: '兵庫「キャッチコピーは<br>あんま詰め込むもんちゃう！」' },
                    { text: "行政区分<br>どないなっとんねん！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '兵庫「県の中に王国があるやんけ！<br>パスポート要るんかここ！？」' },
                    { text: "欲張りさんやなぁ", 
                        point: 0, type: ['v'], 
                        reaction: '兵庫「日本の縮図より<br>カオスな状況やで・・・」' }
                ]
            },
            { type: 'dialogue', speaker: '兵庫', text: '名前で遊ぶのは<br>そんくらいにしといて' },
            { type: 'dialogue', speaker: '兵庫', text: '兵庫といえば、やっぱ<br>神戸の「ハイカラ文化」やな！' },
            { type: 'dialogue', speaker: '兵庫', text: '昔から外国の文化を取り入れてきたから<br>流行りモンには敏感なんや' },
            { type: 'dialogue', speaker: '兵庫', text: '最新のスイーツとか、カフェとか' },
            { type: 'dialogue', speaker: '兵庫', text: '「インスタ映え」する美味しいモンが<br>いっぱいあるで！' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>流行りものかぁ' },
            { type: 'dialogue', speaker: '山形', text: '山形にもあるよ<br>流行りそうな食べ物' },
            { type: 'dialogue', speaker: '山形', text: '「山形のタピオカ」って言うんだけど' },
            { type: 'dialogue', speaker: '兵庫', text: 'タピオカって<br>まだ流行っとん・・・？' },
            { type: 'dialogue', speaker: '兵庫', text: '・・・まあええか。<br>普通のと何が違うん？' },
            { type: 'dialogue', speaker: '山形', text: '「山形のタピオカ」っていうのは・・・' },
            {
                type: 'prompt', speaker: '山形', text: '山形のソウルフード<br>「玉こんにゃく」のことだよ',
                promptText: '「山形のタピオカ」は<br>「玉こんにゃく」のことだよ',
                tsukkomi: [
                    { text: "タピオカって<br>こんにゃくなん？", 
                        point: 0, type: ['v'], 
                        reaction: '兵庫「・・・なんやちゃうんかい<br>紛らわしいわ」' },
                    { text: "インスタ映え<br>なめとんのか！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '兵庫「茶色一色やないか！<br>キラキラ感ゼロやぞ！渋すぎるわ！」' },
                    { text: "確かに原材料<br>芋やけど！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '兵庫「上手いこと言わんでええねん！<br>玉こんにゃくは、こんにゃくや」' }
                ]
            },
            { type: 'dialogue', speaker: '兵庫', text: 'もっとこう・・・<br>スタイリッシュなんは無いんか？' },
            { type: 'dialogue', speaker: '兵庫', text: '兵庫には「姫路城」があるで！<br>世界遺産で、別名「白鷺城」！' },
            { type: 'dialogue', speaker: '兵庫', text: 'あの真っ白で優美な姿・・・<br>世界中から観光客が来るんや' },
            { type: 'dialogue', speaker: '山形', text: '白い建物なら<br>山形にもすごいのがあるよ' },
            { type: 'dialogue', speaker: '兵庫', text: 'おっ！歴史あるお城か？<br>それとも神戸ポートタワーみたいなやつか？' },
            { type: 'dialogue', speaker: '山形', text: '「スカイタワー41」っていう<br>超高層マンションだよ' },
            { type: 'dialogue', speaker: '兵庫', text: 'タワマンか！<br>まあ都会的でええやん' },
            {
                type: 'prompt', speaker: '山形', text: '田園風景の中にポツンと建ってる<br>東北で最高層のマンションなんだ',
                tsukkomi: [
                    { text: "異物感<br>ありすぎやろ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '兵庫「なんでそんなとこに建てたん！？<br>違和感の塊やないか！」' },
                    { text: "景色<br>最高やろなぁ", 
                        point: 0, type: ['p'], 
                        reaction: '兵庫「360度稲穂ビューやん」' },
                    { text: "姫路城と<br>並ぼうとすんな！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '兵庫「白さの意味が全然ちゃうやろがい！」' }
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '兵庫', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '兵庫', text: 'ツッコミどころが多いってことは<br>ようわかったわ' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '兵庫', text: '・・・・・・' },
            { type: 'dialogue', speaker: '兵庫', text: 'それでええんかい！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 山口 ---------------------------------------------------------------------------------------------------------
    'yamaguchi': {
        scenario: [
            { type: 'dialogue', speaker: '山口', text: 'はいどうもー！<br>山口県です！' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '山口', text: '山口といえば<br>日本の歴史を動かした県じゃ！' },
            { type: 'dialogue', speaker: '山口', text: '伊藤博文をはじめ<br>総理大臣の輩出数は日本一！' },
            { type: 'dialogue', speaker: '山口', text: '日本をリードする<br>「強いリーダー」が多いんよ' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>カリスマ性があるんだね' },
            { type: 'dialogue', speaker: '山形', text: '山形にも圧倒的な存在感を放つ<br>超重要人物がいるよ' },
            { type: 'dialogue', speaker: '山口', text: 'ほう！維新志士のような<br>熱い志を持った人物か？' },
            { type: 'dialogue', speaker: '山形', text: '「桃色ウサヒ」っていう<br>ピンク色のウサギなんだけど' },
            { type: 'dialogue', speaker: '山口', text: 'ウサギ・・・？<br>まあ、見た目より中身が大事じゃけぇな' },
            { type: 'dialogue', speaker: '山形', text: '特徴は<br>無個性・無軌道・無表情' },
            { type: 'dialogue', speaker: '山形', text: 'キャッチコピーは<br>「朝日が育んだ圧倒的無個性」' },
            {
                type: 'prompt', speaker: '山形', text: '山形県朝日町の<br>非公式PRキャラクターだよ',
                tsukkomi: [
                    { text: "やる気<br>あんのかよ！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '山口「日本の未来を<br>任せられんわ！」' },
                    { text: "逆に大物<br>かもしれん", 
                        point: 0, type: ['p','t'], 
                        reaction: '山口「悟りを開いた<br>仙人みたいなやつじゃ」' },
                    { text: "超重要人物<br>じゃないじゃろ！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '山口「ただの着ぐるみよね・・・」' }
                ]
            },
            { type: 'dialogue', speaker: '山口', text: '個性がなさすぎるのも問題じゃな・・・' },
            { type: 'dialogue', speaker: '山口', text: '山口県民はもっと情熱的じゃ！<br>食文化だって熱いぞ！' },
            { type: 'dialogue', speaker: '山口', text: 'なんと言っても「瓦そば」！' },
            { type: 'dialogue', speaker: '山口', text: '熱々に焼けた屋根瓦の上で<br>茶そばを焼いて食べるんじゃ！' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>瓦の上で！すごいね' },
            { type: 'dialogue', speaker: '山形', text: '山形も<br>麺類はよく食べるよ' },
            { type: 'dialogue', speaker: '山形', text: 'ラーメンの消費額が<br>日本一だったりするし' },
            { type: 'dialogue', speaker: '山口', text: '日本一！？<br>そんなに食うんか' },
            { type: 'dialogue', speaker: '山形', text: 'それにちなんで、山形県の<br>新しい名前ができたんだ' },
            { type: 'dialogue', speaker: '山口', text: '新しい名前・・・？' },
            { type: 'dialogue', speaker: '山形', text: '山形改め・・・' },
            {
                type: 'prompt', speaker: '山形', text: '「ラーメン県そば王国やまがた」だよ',
                tsukkomi: [
                    { text: "県の中に<br>国作っちょる！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '山口「行政区分<br>どうなっちょるん！？」' },
                    { text: "名前が<br>長すぎるわ！", 
                        point: 1, type: ['t', 'p'], 
                        reaction: '山口「履歴書の住所欄に<br>書ききれんじゃろ！」' },
                    { text: "山形と山口って<br>似ちょるな", 
                        point: 0, type: ['v'], 
                        reaction: '山口「子音が全部一緒じゃ」' }
                ]
            },
            { type: 'dialogue', speaker: '山口', text: 'まあ<br>麺類はもうええわ' },
            { type: 'dialogue', speaker: '山口', text: '山口には、もっと高級で<br>危険な大人の味があるんじゃ' },
            { type: 'dialogue', speaker: '山口', text: '「ふぐ」じゃよ、「ふぐ」！' },
            { type: 'dialogue', speaker: '山口', text: '本場の下関では幸福を呼ぶ魚として<br>「ふく」って呼ぶんじゃ' },
            { type: 'dialogue', speaker: '山口', text: '毒がある危険な魚を食す・・・<br>これぞ大人の食文化じゃろ？' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>大人の味だね' },
            { type: 'dialogue', speaker: '山形', text: '山形でも<br>毒を持つ生き物が食べれるよ' },
            { type: 'dialogue', speaker: '山口', text: 'ほう！<br>マムシでも食うんか？' },
            { type: 'dialogue', speaker: '山形', text: 'ううん、「クラゲ」だよ' },
            { type: 'dialogue', speaker: '山口', text: 'クラゲ！？<br>まあ確かに毒はあるが・・・' },
            { type: 'dialogue', speaker: '山形', text: '世界一の展示数を誇る<br>「加茂水族館」があるんだけど' },
            { type: 'dialogue', speaker: '山口', text: 'おお、水族館か！<br>幻想的でええな' },
            {
                type: 'prompt', speaker: '山形', text: '見終わった後は売店で<br>「クラゲアイス」が食られるよ',
                tsukkomi: [
                    { text: "眺めたあと<br>食うんか！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '山口「さっきまで幻想的じゃったのに！<br>怖いわ！」' },
                    { text: "なんでアイスに<br>したんじゃ！", 
                        point: 1, type: ['t', 'v'], 
                        reaction: '山口「あんまスイーツに<br>クラゲ入れんじゃろ！」' },
                    { text: "毒のレベル<br>が違うわ！", 
                        point: 0, type: ['v'], 
                        reaction: '山口「フグと一緒にすんな！」' }
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '山口', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '山口', text: 'ツッコミどころが多いってことは<br>ようわかった' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '山口', text: '・・・・・・' },
            { type: 'dialogue', speaker: '山口', text: 'それでええんか！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },

    // -------- 香川 --------------------------------------------------------------------------------------------------------
    'kagawa': {
        scenario: [
            { type: 'dialogue', speaker: '香川', text: 'はいどうも〜！<br>香川県です！' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '香川', text: '香川といえば<br>やっぱり「うどん」！' },
            { type: 'dialogue', speaker: '香川', text: '県内にはコンビニより<br>うどん屋の方が多いけんな' },
            { type: 'dialogue', speaker: '香川', text: '「信号機の数よりうどん屋が多い」って<br>言われよるくらいや' },
            { type: 'dialogue', speaker: '香川', text: 'もはや主食を超えて<br>インフラみたいなもんやな' },
            { type: 'dialogue', speaker: '香川', text: 'やけん、県名を<br>「うどん県」に改名したんや' },
            { type: 'dialogue', speaker: '香川', text: 'これくらい潔い名前が<br>一番わかりやすいんよ' },
            { type: 'dialogue', speaker: '山形', text: 'おっ、改名したんだ<br>奇遇だね' },
            { type: 'dialogue', speaker: '山形', text: '山形もラーメンとそばが有名で<br>それにちなんで新しい名前をつけたよ' },
            { type: 'dialogue', speaker: '香川', text: 'へえ、なんて名前にしたん？' },
            {
                type: 'prompt', speaker: '山形', text: '「ラーメン県そば王国やまがた」だよ',
                tsukkomi: [
                    { text: "県の中に<br>国作っとるやん！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '香川「行政区分どうなっとん！？」' },
                    { text: "名前が<br>長すぎるわ！", 
                        point: 1, type: ['t', 'p'], 
                        reaction: '香川「履歴書の住所欄に<br>書ききれんやろ！」' },
                    { text: "うどんも<br>入れようぜ", 
                        point: 0, type: ['v'], 
                        reaction: '香川「ラーメン県うどん市<br>そば王国でどうや？」' }
                ]
            },
            { type: 'dialogue', speaker: '香川', text: '要素多すぎやろ・・・' },
            { type: 'dialogue', speaker: '香川', text: '香川を見習って<br>もっとコンパクトにいかな' },
            { type: 'dialogue', speaker: '香川', text: '香川は日本一面積が小さい県やけど<br>その分ギュッと詰まっとるんよ' },
            { type: 'dialogue', speaker: '山形', text: 'へぇ〜<br>小さいんだね' },
            { type: 'dialogue', speaker: '山形', text: '山形は面積が大きいから<br>イベントもビッグスケールだよ' },
            { type: 'dialogue', speaker: '香川', text: 'ビッグスケール？<br>どんなんするん？' },
            { type: 'dialogue', speaker: '山形', text: '人間を将棋の駒に見立てた<br>「人間将棋」とか' },
            { type: 'dialogue', speaker: '香川', text: '人間が・・・駒に・・・？' },
            {
                type: 'prompt', speaker: '山形', text: 'あと、直径6.5mの巨大鍋で<br>大規模な芋煮会をやるよ',
                promptText: '人が駒となって動く人間将棋と<br>巨大鍋とバックホーを使う芋煮会をするよ',
                tsukkomi: [
                    { text: "変なイベントばっか<br>すんなや！", 
                        point: 1, type: ['t', 'p', 'v'], 
                        reaction: '香川「その広い土地<br>もっと有意義に使えるやろ」' },
                    { text: "なんでもかんでも<br>巨大化させすぎや！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '香川「ビッグスケールって<br>ホンマに巨大化させただけやん！」' },
                    { text: "そのイベントスペース<br>分けてほしいわ", 
                        point: 0, type: ['v'], 
                        reaction: '香川「有り余っとんのやろ？」' }
                ]
            },

            { type: 'dialogue', speaker: '香川', text: 'でも最近はやっぱ<br>「インスタ映え」スポットやな' },
            { type: 'dialogue', speaker: '香川', text: '「<ruby>父母ヶ浜<rt>ちちぶがはま</rt></ruby>」って知っとるか？' },
            { type: 'dialogue', speaker: '香川', text: '「日本のウユニ塩湖」って呼ばれてて<br>水面が鏡みたいになる絶景なんや！' },
            { type: 'dialogue', speaker: '山形', text: 'へえ〜行ってみたいな<br>「日本のウユニ塩湖」ね' },
            { type: 'dialogue', speaker: '山形', text: '山形には<br>「山形のタピオカ」があるよ' },
            { type: 'dialogue', speaker: '香川', text: '山形のタピオカ？それは・・・<br>山形のタピオカやん' },
            { type: 'dialogue', speaker: '香川', text: 'なんか珍しいん？<br>インスタ映えするん？' },
            { type: 'dialogue', speaker: '山形', text: '「山形のタピオカ」は・・・' },
            {
                type: 'prompt', speaker: '山形', text: '山形のソウルフード<br>「玉こんにゃく」のことだよ',
                tsukkomi: [
                    { text: "確かに<br>ほぼタピオカやん", 
                        point: 0, type: ['v'], 
                        reaction: '香川「原材料芋やし<br>まんまるやん」' },
                    { text: "タピオカ<br>ちゃうやん！", 
                        point: 1, type: ['v', 'p'], 
                        reaction: '香川「インスタ映えできるか？<br>こんにゃくで・・・」' },
                    { text: "いや確かに原材料<br>芋やけど！", 
                        point: 3, type: ['t', 'p', 'v'], 
                        reaction: '香川「上手いこと言いやがって・・・」' }
                ]
            },

            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '香川', text: 'う〜ん<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '香川', text: 'ツッコミどころが多いってことは<br>ようわかったわ' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '香川', text: '・・・・・・' },
            { type: 'dialogue', speaker: '香川', text: 'それでええんか！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
        ]
    },
    
    // -------- 愛媛 ---------------------------------------------------------------------------------------------------------
    'ehime': {
        scenario: [
            { type: 'dialogue', speaker: '愛媛', text: 'はいどうもー、愛媛県よ〜' },
            { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
            { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
            { type: 'dialogue', speaker: '愛媛', text: '愛媛には「道後温泉」っていう<br>日本最古の温泉があるんよ' },
            { type: 'dialogue', speaker: '愛媛', text: '山形さんも温泉多いけど' },
            { type: 'dialogue', speaker: '愛媛', text: 'やっぱお風呂はポカポカして<br>癒やされるんがええよね' },
            { type: 'dialogue', speaker: '山形', text: 'そうだね<br>雪国だから冬は寒いし' },
            { type: 'dialogue', speaker: '山形', text: 'でも夏は暑いから<br>温泉よりも「冷やしシャンプー」かな' },
            { type: 'dialogue', speaker: '愛媛', text: '冷やしシャンプー・・・？' },
            { type: 'dialogue', speaker: '山形', text: '床屋さんでやってもらうんだ' },
            { type: 'dialogue', speaker: '愛媛', text: '頭が凍ってしまいそうやね・・・' },
            { type: 'dialogue', speaker: '山形', text: '暑い夏には最高だよ' },
            { type: 'dialogue', speaker: '山形', text: 'あと、ラーメン屋さんが<br>冷やしラーメンを始めたり' },
            { type: 'dialogue', speaker: '愛媛', text: 'はあ？<br>冷やしラーメン・・・？' },
            { type: 'dialogue', speaker: '山形', text: '「冷やし中華始めました」<br>みたいな感じで' },
            {
                type: 'prompt', speaker: '山形', text: '山形の夏は<br>いろんなものが冷えてるよ',
                promptText: '冷やし中華始めましたみたいな感じで<br>山形の夏はいろんなものが冷えてるよ',
                tsukkomi: [
                    { text: "暑がりすぎやろ！", 
                        point: 1, 
                        type: ['t', 'p'], 
                        reaction: '愛媛「山形の夏はそんなに暑いん！？」' },
                    { text: "冷やし中華だけで<br>十分やろ！", 
                        point: 3, 
                        type: ['t', 'p', 'v'], 
                        reaction: '山形「最近は冷やしマスクもあるよ」' },
                    { text: "お腹<br>壊さんようにね", 
                        point: 0, 
                        type: ['v'], 
                        reaction: '愛媛「冷やしすぎもいかんよ<br>体冷えるけん」' }
                ]
            },
            { type: 'dialogue', speaker: '愛媛', text: '刺激が強すぎるわい...' },
            { type: 'dialogue', speaker: '愛媛', text: 'もっとこう、瀬戸内の海みたいに<br>優雅なものはないんかな？' },
            { type: 'dialogue', speaker: '愛媛', text: 'うちは「鯛めし」が自慢よ' },
            { type: 'dialogue', speaker: '愛媛', text: 'お刺身のタイプと、<br>炊き込みタイプがあるんよ' },
            { type: 'dialogue', speaker: '山形', text: '海の幸なら山形にもあるよ<br>加茂水族館の「クラゲ」とか' },
            { type: 'dialogue', speaker: '愛媛', text: 'ク、クラゲ...？' },
            { type: 'dialogue', speaker: '愛媛', text: '海の幸って言っても<br>観賞用やろ...' },
            {
                type: 'prompt', speaker: '山形', text: '水族館を一通り見終わったら<br>売店でクラゲアイスを食べるんだ',
                tsukkomi: [
                    { text: "クラゲアイス！？<br>変なスイーツやね！", 
                        point: 1, 
                        type: ['t', 'p'], 
                        reaction: '愛媛「食用クラゲなんて<br>中華料理でしか聞かんよ」' },
                    { text: "鯛の餌に<br>しようや", 
                        point: 0, 
                        type: ['v'], 
                        reaction: '山形「食物連鎖だね」' },
                    { text: "さっき見たやつ<br>食うんかい！", 
                        point: 3, 
                        type: ['t', 'p', 'v'], 
                        reaction: '愛媛「今まで『綺麗やね〜』言うて愛でよったのに...」' }
                ]
            },
            { type: 'dialogue', speaker: '愛媛', text: 'なんかしんどなってきたわ...' },
            { type: 'dialogue', speaker: '愛媛', text: '愛媛に帰って<br>「いもたき」でもして落ち着きたい...' },
            { type: 'dialogue', speaker: '愛媛', text: '河原で鍋囲んで食べるんよね<br>素朴でええよね〜' },
            { type: 'dialogue', speaker: '山形', text: 'あ、里芋を煮るやつ？' },
            { type: 'dialogue', speaker: '山形', text: 'それなら山形の「芋煮」も負けてないよ' },
            { type: 'dialogue', speaker: '山形', text: 'なんといっても、<br>「日本一」の芋煮会を目指したからね' },
            { type: 'dialogue', speaker: '愛媛', text: '日本一？<br>最高の味を追求したん？' },
            { type: 'dialogue', speaker: '山形', text: '味というか・・・' },
            {
                type: 'prompt', speaker: '山形', text: '直径6.5mの大鍋に具材を入れて<br>バックホーで調理する芋煮会だよ',
                tsukkomi: [
                    { text: "工事現場<br>やろが！", 
                        point: 1, 
                        type: ['p', 'v'], 
                        reaction: '愛媛「調理器具の概念壊れるわい！」' },
                    { text: "それって<br>衛生的にどうなん？", 
                        point: 0, 
                        type: ['t', 'v'], 
                        reaction: '山形「新品の重機を買って潤滑油にバターを塗ってるから大丈夫だよ」' },
                    { text: "日本一の<br>“デカさ”かい！", 
                        point: 3, 
                        type: ['t', 'p', 'v'], 
                        reaction: '愛媛「味やのうてサイズの話かい！<br>予想の斜め上すぎるわ！」' }
                ]
            },
            { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
            { type: 'dialogue', speaker: '愛媛', text: 'ほうやね<br>とりあえず・・・' },
            { type: 'dialogue', speaker: '愛媛', text: 'ツッコミどころが多すぎる<br>ってことはようわかったわ' },
            { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
            { type: 'dialogue', speaker: '愛媛', text: '・・・・・・' },
            { type: 'dialogue', speaker: '愛媛', text: 'ほんまにそれでええんかい！！' },
            { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！！' },
        ]
    },
    
    // -------- 沖縄 -----------------------------------------------------------------------------------------------------
    'okinawa': {
    scenario: [
        { type: 'dialogue', speaker: '沖縄', text: 'ハイサイ！<br>沖縄県さ〜' },
        { type: 'dialogue', speaker: '山形', text: '山形県で〜す' },
        { type: 'dialogue', speaker: '山形', text: '今日は県の形だけでも<br>覚えて帰ってくださ〜い' },
        { type: 'dialogue', speaker: '沖縄', text: '沖縄といえばシーサーさぁ<br>家の守り神だね' },
        { type: 'dialogue', speaker: '沖縄', text: '伝説上の生き物だけど<br>家族みたいに愛されてるわけさ' },
        { type: 'dialogue', speaker: '山形', text: '伝説上の生き物なら<br>山形でも愛でられてるよ' },
        { type: 'dialogue', speaker: '沖縄', text: 'へぇ〜、なになに？<br>龍とかキジムナー的な？' },
        { type: 'dialogue', speaker: '山形', text: 'ケサランパサラン' },
        { type: 'dialogue', speaker: '沖縄', text: 'え？<br>あの白い毛玉！？' },
        { type: 'dialogue', speaker: '山形', text: 'そうだよ' },
        { type: 'dialogue', speaker: '山形', text: '桐の箱に入れて<br>おしろいをあげて育てるんだ' },
        { type: 'dialogue', speaker: '沖縄', text: 'あれ正体不明の<ruby>未確認生物<rt>UMA</rt></ruby>だよね！？' },
        { type: 'dialogue', speaker: '沖縄', text: 'ペット感覚なの！？' },
        
        { type: 'prompt', speaker: '山形', text: '水族館にも<br>展示されてるよ',
            tsukkomi: [
                { text: "海の生き物じゃ<br>ないでしょ！", 
                    point: 1, type: ['v', 't'],
                    reaction: '沖縄「どっちかっていうと<br>動物園じゃない・・・？」' },
                { text: "美ら海水族館にも<br>展示して〜！", 
                    point: 0, type: ['v','p'],
                    reaction: '沖縄「未確認生物<br>確認した〜い」' },
                { text: "未確認生物<br>確認しちゃってるよ！", 
                    point: 3, type: ['t', 'p', 'v'],
                    reaction: '沖縄「展示してる場合じゃないでしょ！<br>調べて調べて！」' }
            ]
        },
        { type: 'dialogue', speaker: '沖縄', text: 'はぁ・・・<br>でーじパニックさぁ' },
        { type: 'dialogue', speaker: '沖縄', text: 'こういう時はスカッとするものを飲んで<br>リフレッシュしたいわけよ' },
        { type: 'dialogue', speaker: '山形', text: 'スカッとするもの？' },
        { type: 'dialogue', speaker: '沖縄', text: 'そう、沖縄のソウルドリンク<br>「ルートビア」！' },
        { type: 'dialogue', speaker: '沖縄', text: 'ハーブでスースーして<br>目が覚めるよ〜' },
        { type: 'dialogue', speaker: '沖縄', text: '・・・まあ、一部では<br>「飲む湿布」って言われてるけど' },
        { type: 'dialogue', speaker: '沖縄', text: 'でもそのスースー感が<br>暑い夏には最高さぁ' },
        { type: 'dialogue', speaker: '山形', text: '確かに、涼を取るなら<br>スースー感だよね' },
        { type: 'dialogue', speaker: '沖縄', text: '山形さんの夏は<br>どんな風に涼を取るの？' },
        { type: 'dialogue', speaker: '山形', text: '山形の夏は<br>冷やし中華と・・・' },
        { type: 'dialogue', speaker: '沖縄', text: 'だからよ〜<br>夏といえばそれだよね' },
        { type: 'prompt', speaker: '山形', text: '冷やしラーメン、冷やしシャンプー<br>冷やしマスクとか',
            tsukkomi: [
                { text: "冷やしルートビア<br>はじめました〜", 
                    point: 0, type: ['v'], 
                    reaction: '沖縄「やっぱキンキンに冷えてたほうが<br>まーさんだよね」' },
                { text: "なんでもかんでも<br>冷やしすぎ！", 
                    point: 3, type: ['t', 'p', 'v'], 
                    reaction: '沖縄「結構<br>力技で涼取るんだね・・・」' },
                { text: "山形の夏って<br>そんなに暑いの！？", 
                    point: 1, type: ['p', 'v'], 
                    reaction: '沖縄「暑さ対策<br>ちばりよー！」' }
            ]
        },
        { type: 'dialogue', speaker: '沖縄', text: '話聞いてるだけで<br>寒気がしてきたさぁ' },
        { type: 'dialogue', speaker: '沖縄', text: '体が冷えたから<br>温かいものでも食べたいわけよ' },
        { type: 'dialogue', speaker: '山形', text: '温かいものなら<br>山形は「芋煮」が有名だよ' },
        { type: 'dialogue', speaker: '沖縄', text: 'ああ、里芋のお鍋だね<br>響きが素朴で、平和そうでいいさぁ〜' },
        { type: 'dialogue', speaker: '山形', text: '河原でみんなで作るんだ<br>美味しいよ' },
        { type: 'dialogue', speaker: '沖縄', text: 'いいはずよ〜、癒やされそう' },
        { type: 'dialogue', speaker: '山形', text: '日本一の芋煮会フェスティバルは<br>すごく盛り上がるんだ' },
        { type: 'dialogue', speaker: '沖縄', text: '日本一・・・？<br>なんで日本一な訳？' },
        { type: 'prompt', speaker: '山形', text: '直径6.5mの鍋とバックホーで<br>3万食の芋煮を作るんだ',
            tsukkomi: [
                { text: "サイズ感が<br>日本一なのかよ！", 
                    point: 3, type: ['t', 'p', 'v'], 
                    reaction: '沖縄「芋煮会、巨大化させちゃいました<br>ってこと！？」' },
                { text: "ジンベエザメの方が<br>大きいかも", 
                    point: 0, type: ['t', 'v'], 
                    reaction: '山形「負けたか〜」' },
                { text: "隠し味は<br>潤滑油！？", 
                    point: 1, type: ['p', 'v'], 
                    reaction: '山形「潤滑油替わりに<br>バターを塗ってるよ」' }
            ]
        },
        { type: 'dialogue', speaker: '山形', text: 'どう？<br>山形のこと、だいたいわかった？' },
        { type: 'dialogue', speaker: '沖縄', text: 'う〜ん<br>とりあえず・・・' },
        { type: 'dialogue', speaker: '沖縄', text: 'ツッコミどころが多いってことは<br>わかったさぁ' },
        { type: 'dialogue', speaker: '山形', text: 'それが山形の魅力だ！' },
        { type: 'dialogue', speaker: '沖縄', text: '・・・・・・' },
        { type: 'dialogue', speaker: '沖縄', text: 'それでいいわけ！？' },
        { type: 'ending', speaker: 'both', text: 'どうも<br>ありがとうございました〜！' },
    ]
    },

};

